M48
; DRILL file {KiCad (6.0.7)} date Fri Nov  4 16:49:28 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-11-04T16:49:28+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0276
%
G90
G05
T1
X4.8752Y-3.4766
X4.9252Y-3.4766
X4.9752Y-3.4766
X5.0252Y-3.4766
X5.0752Y-3.4766
T0
M30
